/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stddef.h>
#include <stdint.h>

#define REG32(address) (*(volatile uint32_t *)(address))

#define RCC_BASE (0x40023800UL)
#define RCC_AHB1ENR REG32(RCC_BASE + 0x30UL)
#define RCC_APB1ENR REG32(RCC_BASE + 0x40UL)

#define GPIOD_BASE (0x40020C00UL)
#define GPIOD_MODER REG32(GPIOD_BASE + 0x00UL)
#define GPIOD_OTYPER REG32(GPIOD_BASE + 0x04UL)
#define GPIOD_OSPEEDR REG32(GPIOD_BASE + 0x08UL)
#define GPIOD_PUPDR REG32(GPIOD_BASE + 0x0CUL)
#define GPIOD_AFRH REG32(GPIOD_BASE + 0x24UL)

#define USART3_BASE (0x40004800UL)
#define USART3_SR REG32(USART3_BASE + 0x00UL)
#define USART3_DR REG32(USART3_BASE + 0x04UL)
#define USART3_BRR REG32(USART3_BASE + 0x08UL)
#define USART3_CR1 REG32(USART3_BASE + 0x0CUL)
#define USART3_CR2 REG32(USART3_BASE + 0x10UL)
#define USART3_CR3 REG32(USART3_BASE + 0x14UL)

#define SYST_CSR REG32(0xE000E010UL)
#define SYST_RVR REG32(0xE000E014UL)
#define SYST_CVR REG32(0xE000E018UL)

#define HSI_HZ (16000000UL)
#define DEBUG_UART_BAUD (115200UL)

#define RCC_AHB1ENR_GPIODEN (1UL << 3)
#define RCC_APB1ENR_USART3EN (1UL << 18)

#define USART_SR_TXE (1UL << 7)
#define USART_CR1_TE (1UL << 3)
#define USART_CR1_RE (1UL << 2)
#define USART_CR1_UE (1UL << 13)

#define SYST_CSR_ENABLE (1UL << 0)
#define SYST_CSR_CLKSOURCE (1UL << 2)
#define SYST_CSR_COUNTFLAG (1UL << 16)

#define MAVLINK_STX_V2 (0xFD)
#define MAVLINK_MSG_ID_HEARTBEAT (0U)
#define MAVLINK_MSG_HEARTBEAT_LEN (9U)
#define MAVLINK_MSG_HEARTBEAT_CRC_EXTRA (50U)

static uint8_t mavlink_sequence;

void SystemInit(void)
{
}

static void debug_uart_init(void)
{
    RCC_AHB1ENR |= RCC_AHB1ENR_GPIODEN;
    RCC_APB1ENR |= RCC_APB1ENR_USART3EN;
    (void)RCC_AHB1ENR;
    (void)RCC_APB1ENR;

    /* NUCLEO-F446ZE ST-LINK VCP defaults to USART3 TX/RX on PD8/PD9. */
    GPIOD_MODER &= ~((3UL << (8U * 2U)) | (3UL << (9U * 2U)));
    GPIOD_MODER |= (2UL << (8U * 2U)) | (2UL << (9U * 2U));

    GPIOD_AFRH &= ~((0xFUL << ((8U - 8U) * 4U)) |
                    (0xFUL << ((9U - 8U) * 4U)));
    GPIOD_AFRH |= (7UL << ((8U - 8U) * 4U)) |
                  (7UL << ((9U - 8U) * 4U));

    GPIOD_OTYPER &= ~((1UL << 8U) | (1UL << 9U));
    GPIOD_OSPEEDR |= (3UL << (8U * 2U)) | (3UL << (9U * 2U));
    GPIOD_PUPDR &= ~((3UL << (8U * 2U)) | (3UL << (9U * 2U)));
    GPIOD_PUPDR |= (1UL << (9U * 2U));

    USART3_CR1 = 0;
    USART3_CR2 = 0;
    USART3_CR3 = 0;
    USART3_BRR = (HSI_HZ + (DEBUG_UART_BAUD / 2UL)) / DEBUG_UART_BAUD;
    USART3_CR1 = USART_CR1_TE | USART_CR1_RE | USART_CR1_UE;
}

static void debug_uart_write_byte(uint8_t value)
{
    while ((USART3_SR & USART_SR_TXE) == 0U) {
    }

    USART3_DR = value;
}

static void debug_uart_write(const uint8_t *data, size_t length)
{
    for (size_t i = 0; i < length; i++) {
        debug_uart_write_byte(data[i]);
    }
}

static void systick_init_1ms(void)
{
    SYST_RVR = (HSI_HZ / 1000UL) - 1UL;
    SYST_CVR = 0;
    SYST_CSR = SYST_CSR_CLKSOURCE | SYST_CSR_ENABLE;
}

static void delay_ms(uint32_t milliseconds)
{
    while (milliseconds > 0U) {
        while ((SYST_CSR & SYST_CSR_COUNTFLAG) == 0U) {
        }

        milliseconds--;
    }
}

static void mavlink_crc_accumulate(uint8_t data, uint16_t *crc)
{
    uint8_t tmp = data ^ (uint8_t)(*crc & 0xFFU);
    tmp ^= (uint8_t)(tmp << 4U);
    *crc = (*crc >> 8U) ^ ((uint16_t)tmp << 8U) ^
           ((uint16_t)tmp << 3U) ^ ((uint16_t)tmp >> 4U);
}

static void mavlink_send_heartbeat(void)
{
    uint8_t frame[10U + MAVLINK_MSG_HEARTBEAT_LEN + 2U];
    size_t index = 0;

    frame[index++] = MAVLINK_STX_V2;
    frame[index++] = MAVLINK_MSG_HEARTBEAT_LEN;
    frame[index++] = 0; /* incompat_flags */
    frame[index++] = 0; /* compat_flags */
    frame[index++] = mavlink_sequence++;
    frame[index++] = 1; /* system id */
    frame[index++] = 1; /* component id */
    frame[index++] = (uint8_t)(MAVLINK_MSG_ID_HEARTBEAT & 0xFFU);
    frame[index++] = (uint8_t)((MAVLINK_MSG_ID_HEARTBEAT >> 8U) & 0xFFU);
    frame[index++] = (uint8_t)((MAVLINK_MSG_ID_HEARTBEAT >> 16U) & 0xFFU);

    frame[index++] = 0; /* custom_mode */
    frame[index++] = 0;
    frame[index++] = 0;
    frame[index++] = 0;
    frame[index++] = 0; /* MAV_TYPE_GENERIC */
    frame[index++] = 8; /* MAV_AUTOPILOT_INVALID */
    frame[index++] = 0; /* base_mode */
    frame[index++] = 3; /* MAV_STATE_STANDBY */
    frame[index++] = 3; /* MAVLink version */

    uint16_t crc = 0xFFFFU;
    for (size_t i = 1; i < index; i++) {
        mavlink_crc_accumulate(frame[i], &crc);
    }
    mavlink_crc_accumulate(MAVLINK_MSG_HEARTBEAT_CRC_EXTRA, &crc);

    frame[index++] = (uint8_t)(crc & 0xFFU);
    frame[index++] = (uint8_t)(crc >> 8U);

    debug_uart_write(frame, index);
}

int main(void)
{
    debug_uart_init();
    systick_init_1ms();

    for (;;) {
        mavlink_send_heartbeat();
        delay_ms(1000);
    }
}
